FinalProject/Controllers/AdminController.cs
using FinalProject.AdditionalModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FinalProject.Models;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace FinalProject.Controllers
{
    public class AdminController : Controller
    {
        private readonly NorthwindContext _northwindContext;

        public AdminController(NorthwindContext northwindContext)
        {
            _northwindContext = northwindContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Customer()
        {
            var model = await _northwindContext.Customers.Take(50).OrderBy(c => c.ContactName).ToListAsync();
            return View(model);
        }

        public async Task<IActionResult> Supplier()
        {
            var model = await _northwindContext.Suppliers.ToListAsync();
            return View(model);
        }

        public async Task<IActionResult> Product()
        {
            var query = from od in _northwindContext.OrderDetails
                        join p in _northwindContext.Products on od.ProductId equals p.ProductId
                        join c in _northwindContext.Categories on p.CategoryId equals c.CategoryId
                        group od by new { p.ProductId, p.ProductName, p.QuantityPerUnit, p.UnitPrice, p.UnitsInStock, c.CategoryName } into grouped
                        select new ProductViewModel
                        {
                            ProductId = grouped.Key.ProductId,
                            ProductName = grouped.Key.ProductName,
                            QuantityPerUnit = grouped.Key.QuantityPerUnit,
                            UnitPrice = grouped.Key.UnitPrice,
                            UnitsInStock = grouped.Key.UnitsInStock,
                            CategoryName = grouped.Key.CategoryName,
                            TotalQuantity = grouped.Sum(od => od.Quantity)
                        };

            var model = await query.ToListAsync();

            return View(model);
        }

        public async Task<IActionResult> CustomerRedact(Customer customerData)
        {
            var customerToRedact = await _northwindContext.Customers.FirstOrDefaultAsync(c => c.CustomerId == customerData.CustomerId);

            if (customerToRedact == null)
            {
                TempData["ErrorMessageRedact"] = "Customer not found";
                return RedirectToAction("Customer");
            }
            else
            {
                if (customerData.CompanyName != null)
                {
                    customerToRedact.CompanyName = customerData.CompanyName;
                }
                if (customerData.ContactName != null)
                {
                    customerToRedact.ContactName = customerData.ContactName;
                }
                if (customerData.ContactTitle != null)
                {
                    customerToRedact.ContactTitle = customerData.ContactTitle;
                }
                if (customerData.Address != null)
                {
                    customerToRedact.Address = customerData.Address;
                }
                if (customerData.City != null)
                {
                    customerToRedact.City = customerData.City;
                }
                if (customerData.Region != null)
                {
                    customerToRedact.Region = customerData.Region;
                }
                if (customerData.PostalCode != null)
                {
                    customerToRedact.PostalCode = customerData.PostalCode;
                }
                if (customerData.Country != null)
                {
                    customerToRedact.Country = customerData.Country;
                }
                if (customerData.Phone != null)
                {
                    customerToRedact.Phone = customerData.Phone;
                }
                if (customerData.Fax != null)
                {
                    customerToRedact.Fax = customerData.Fax;
                }

                TempData["SuccessMessageRedact"] = "Entity was updated";
                _northwindContext.SaveChanges();

                return RedirectToAction("Customer");
            }
        }

        public async Task<IActionResult> CustomerDelete(string CustomerId)
        {
            var customerToDelete = await _northwindContext.Customers.FirstOrDefaultAsync(c => c.CustomerId == CustomerId);

            if (customerToDelete == null)
            {
                TempData["ErrorMessageDelete"] = "Customer not found";
                return RedirectToAction("Customer");
            }
            else
            {
                var ordersToDelete = await _northwindContext.Orders.Where(o => o.CustomerId == customerToDelete.CustomerId).ToListAsync();

                foreach (var order in ordersToDelete)
                {
                    var orderDetailsToDelete = await _northwindContext.OrderDetails.Where(od => od.OrderId == order.OrderId).ToListAsync();
                    _northwindContext.OrderDetails.RemoveRange(orderDetailsToDelete);
                }

                _northwindContext.Orders.RemoveRange(ordersToDelete);
                _northwindContext.Customers.Remove(customerToDelete);


                TempData["SuccessMessageDelete"] = "User was deleted";
                _northwindContext.SaveChanges();

                return RedirectToAction("Customer");
            }
        }

        public async Task<IActionResult> CustomerAdd(Customer newCustomer)
        {
            if (ModelState.IsValid)
            {
                _northwindContext.Customers.Add(newCustomer);
                await _northwindContext.SaveChangesAsync();
                TempData["SuccessMessageAdd"] = "Customer added successfully";
            }
            else
            {
                TempData["ErrorMessageAdd"] = "Invalid customer data";
            }

            return RedirectToAction("Customer");
        }

        public async Task<IActionResult> ProductRedact(Product productData)
        {
            var productToRedact = await _northwindContext.Products.FirstOrDefaultAsync(p => p.ProductId == productData.ProductId);

            if (productToRedact == null)
            {
                TempData["ErrorMessageRedact"] = "Product not found";
                return RedirectToAction("Product");
            }
            else
            {
                if (productData.ProductName != null)
                {
                    productToRedact.ProductName = productData.ProductName;
                }
                if (productData.QuantityPerUnit != null)
                {
                    productToRedact.QuantityPerUnit = productData.QuantityPerUnit;
                }
                if (productData.UnitPrice != null)
                {
                    productToRedact.UnitPrice = productData.UnitPrice;
                }
                if (productData.UnitsInStock != null)
                {
                    productToRedact.UnitsInStock = productData.UnitsInStock;
                }
                if (productData.UnitsOnOrder != null)
                {
                    productToRedact.UnitsOnOrder = productData.UnitsOnOrder;
                }
                if (productData.ReorderLevel != null)
                {
                    productToRedact.ReorderLevel = productData.ReorderLevel;
                }
                productToRedact.Discontinued = false;

                TempData["SuccessMessageRedact"] = "Entity was updated";
                _northwindContext.SaveChanges();

                return RedirectToAction("Product");
            }
        }

        public async Task<IActionResult> ProductDelete(int productId)
        {
            var productToDelete = await _northwindContext.Products.FirstOrDefaultAsync(p => p.ProductId == productId);

            if (productToDelete == null)
            {
                TempData["ErrorMessageDelete"] = "Product not found";
                return RedirectToAction("Product");
            }
            else
            {
                var orderDetailsToDelete = await _northwindContext.OrderDetails
                    .Where(o => o.ProductId == productId)
                    .ToListAsync();

                _northwindContext.OrderDetails.RemoveRange(orderDetailsToDelete);

                _northwindContext.Products.Remove(productToDelete);

                TempData["SuccessMessageDelete"] = "Product was deleted";
                _northwindContext.SaveChanges();

                return RedirectToAction("Product");
            }
        }

        public async Task<IActionResult> ProductAdd(Product newProduct)
        {
            newProduct.Discontinued = false;
            if (ModelState.IsValid)
            {
                _northwindContext.Products.Add(newProduct);
                await _northwindContext.SaveChangesAsync();
                TempData["SuccessMessageAdd"] = "Product added successfully";
            }
            else
            {
                TempData["ErrorMessageAdd"] = "Invalid product data";
            }

            return RedirectToAction("Product");
        }

        public async Task<IActionResult> SupplireRedact(Supplier supplierData)
        {
            var supplierToRedact = await _northwindContext.Suppliers.FirstOrDefaultAsync(s => s.SupplierId == supplierData.SupplierId);

            if (supplierToRedact == null)
            {
                TempData["ErrorMessageRedact"] = "Supplier not found";
                return RedirectToAction("Supplier");
            }
            else
            {
                if (supplierData.CompanyName != null)
                {
                    supplierToRedact.CompanyName = supplierData.CompanyName;
                }
                if (supplierData.ContactName != null)
                {

FinalProject/Controllers/MainPageController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FinalProject.AdditionalModels;
using Microsoft.EntityFrameworkCore;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    public class MainPageController : Controller
    {
        private readonly NorthwindContext _northwindContext;

        public MainPageController(NorthwindContext northwindContext)
        {
            _northwindContext = northwindContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Autorisation");
        }

        [HttpPost]
        public async Task<IActionResult> Search(string searchOption, string searchText)
        {
            var model = new SearchViewModel
            {
                SearchOption = searchOption,
                SearchText = searchText,
                SupplierResults = new List<Supplier>(),
                CategoryResults = new List<Category>(),
                ProductResults = new List<Product>()
            };

            switch (searchOption)
            {
                case "supplier":
                    model.SupplierResults = await _northwindContext.Suppliers
                        .Where(s => s.ContactName.Contains(searchText))
                        .ToListAsync();

                    if (model.SupplierResults.Count == 0)
                    {
                        return View("NotFound", model);
                    }
                    else
                    {
                        return View("Searchpage", model);
                    }

                case "category":
                    model.CategoryResults = await _northwindContext.Categories
                        .Where(c => c.CategoryName.Contains(searchText))
                        .ToListAsync();

                    if (model.CategoryResults.Count == 0)
                    {
                        return View("NotFound", model);
                    }
                    else
                    {
                        return View("Searchpage", model);
                    }

                case "product":
                    model.ProductResults = await _northwindContext.Products
                        .Where(p => p.ProductName.Contains(searchText))
                        .ToListAsync();

                    if (model.ProductResults.Count == 0)
                    {
                        return View("NotFound", model);
                    }
                    else
                    {
                        return View("Searchpage", model);
                    }
                default:
                    return View("Notfound", model);
            }
        }
    }
}

FinalProject/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <title>Your Website</title>
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <div class="header-container">
                <div class="first-part">
                    <div class="logo">
                        <img class="logo-img"src="~/Images/icon.png" alt="Logo">
                    </div>

                    <nav class="header-nav">
                        <a asp-controller="MainPage" asp-action="Index">Home</a>
                        <a asp-controller="Customers" asp-action="Index">Customers</a>
                        <a asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                        <a asp-controller="Product" asp-action="Index">Products</a>
                        <div class="dropdown">
                            <a href="#">Admin</a>
                            <div class="dropdown-content">
                                <a asp-controller="Admin" asp-action="Customer">Customers</a>
                                <a asp-controller="Admin" asp-action="Supplier">Suppliers</a>
                                <a asp-controller="Admin" asp-action="Product">Products</a>
                            </div>
                        </div>
                    </nav>
                </div>

                <div class="second-part">
                    <form asp-controller="Mainpage" asp-action="Search" method="post">
                        <div class="search">
                            <input type="text" name="searchText" placeholder="Search..." required>
                            <button id="search-button"><i class="fas fa-search"></i></button>
                        </div>

                        <div>
                            <label>
                                <input type="radio" name="searchOption" value="supplier" required>
                                Supplier
                            </label>

                            <label>
                                <input type="radio" name="searchOption" value="category" required>
                                Category
                            </label>

                            <label>
                                <input type="radio" name="searchOption" value="product" required>
                                Product
                            </label>
                        </div>
                    </form>

                    <div class="exit"> 
                        <a asp-controller="Autorisation" asp-action="Index"><img src="~/Images/exit.png" alt="Exit"/></a>
                    </div>
                </div>
            </div>
        </header>
    
        @RenderBody()
@*        <div class="page-container">
            <div class="mainpage-container">
                <div class="bg-image"></div>
                @RenderBody()
            </div>
        </div>
*@

        <footer class="footer">
            <div class="social-icons">          
                <a href="https://uk-ua.facebook.com/"><i class="fa-brands fa-facebook"></i></a>
                <a href="https://twitter.com/?lang=ru"><i class="fa-brands fa-twitter"></i></a>
                <a href="https://www.instagram.com/"><i class="fa-brands fa-instagram"></i></i></a>
            </div>

            <div class="footer-info">
                <p>&copy;Tymofii Khomych</p>
            </div>
        </footer>
    </div>
</body>
</html>