FinalProject/Controllers/AutorisationController.cs
using FinalProject.AdditionalModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace FinalProject.Controllers
{
    public class AutorisationController : Controller
    {
        private readonly NorthwindContext _northwindContext;

        public AutorisationController(NorthwindContext northwindContext)
        {
            _northwindContext = northwindContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Autorize(string login, string password)
        {
            var user = await _northwindContext.Users.FirstOrDefaultAsync(u => u.Login == login && 
                u.Password == HashingService.Hash(password));

            if (user != null)
            {
                return RedirectToAction("Index", "Mainpage");
            }
            else
            {
                ViewBag.ErrorMessage = "Користувача не знайдено";
                return View("~/Views/Autorisation/Index.cshtml");
            }
        }
    }
}

FinalProject/Controllers/RegistrationController.cs
using FinalProject.AdditionalModels;
using FinalProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalProject.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly NorthwindContext _northwindContext;

        public RegistrationController(NorthwindContext northwindContext)
        {
            _northwindContext = northwindContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        
        [HttpPost]
        public async Task<IActionResult> Register(RegistrationBindingModel model)
        {
            if (ModelState.IsValid)
            {
                var userWithLogin = await _northwindContext.Users.FirstOrDefaultAsync(u => u.Login == model.Login);
                if (userWithLogin != null)
                {
                    ModelState.AddModelError("Login", "User with this login already exists.");
                    return View("Index");
                }

                var userWithEmail = await _northwindContext.Users.FirstOrDefaultAsync(u => u.Email == model.Email);
                if (userWithEmail != null)
                {
                    ModelState.AddModelError("Email", "User with this email already exists.");
                    return View("Index");
                }

                var NewUser = new User(model.Login, model.Email, HashingService.Hash(model.Password));
                _northwindContext.Users.Add(NewUser);
                await _northwindContext.SaveChangesAsync();
                TempData["SuccessMessage"] = "Registration successful! You can now log in.";
                return RedirectToAction("Index", "Autorisation");
            }
            else
            {
                return View("Index");
            }
        }
    }
}

FinalProject/Views/Autorisation/Index.cshtml
@{
    ViewData["Title"] = "Autorisation";
    Layout = null;
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model FinalProject.Models.User

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/site.css">
    <title>Sea Shipping App</title>
</head>
<body  class="autorisation-body">
    <div class="container">
        <div class="autorisation-form_box">
            <h1>Sea Shipping App</h1>
            <form asp-action="Autorize" method="post">
                @if (TempData["SuccessMessage"] != null)
                {
                    <div class="success-message">
                        @TempData["SuccessMessage"]
                    </div>
                }
                <input type="text" name="login" placeholder="Username" required>
                <input type="password" name="password" placeholder="Password" required>
                <p class="error-message">@ViewBag.ErrorMessage</p>
                <button type="submit">Log In</button>
            </form>
            <p>Don't have an account? <a asp-action="Index" asp-controller="Registration">Sign Up</a></p>
        </div>
    </div>
</body>
</html>